version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: go
    volumes:
      - ./:/pj
    working_dir: /pj
    tty: true
    restart: always